# 1.WHAT IS THE PURPOSE OF FUNCTION IN PYTHON?

# FUNCTION ALLOW YOU TO BREAK DOWN YOUR PROGRAM INTO SMALLER,MANAGEABLE PIECES OF CODE THAT CAN BE REUSED AND 
# CALLED WHENEVER NEEDED. THEY PROMOTE CODE REUSABILITY AND READABILITY.

# 2.HOW DO YOU DEFINE A FUNCTION IN PYTHON?

# YOU DEFINE A FUNCTION USING THE DEF KEYWORD FOLLOWED BY THE FUNCTION NAME AND PARAMETERS ,ENCLOSED IN PARENTHESES.
# THE FUNCTION BODY IS INDENTED BELOW THE DEFINITION.

# 3.WHAT IS PARAMETER AND ARGUMENT IN A FUNCTION?

# PARAMETER ARE THE VARIABLES LISTED INSIDE THE PARENTHESES IN THE FUNCTION DEFINITION ,WHILE ARGUMENT 
# ARE THE VALUES PASSED TO THE FUNCTION WHEN IT IS CALLED.

# 4.WHAT IS THE DIFFERENCE BETWEEN THE RETURN AND PRINT IN A FUNCTION?

# RETURN IS USED TO SEND A VALUE BACK TO THE CALLER OF THE FUNCTION AND TERMINATES THE FUNCTION'S EXECUTION,
# WHILE PRINT IS USED TO DISPLAY A VALUE TO THE CONSOLE BUT DOESNOT AFFECT THE FUNCTIONS OUTPUT OR BEHAVIOR.

# 5.CAN A FUNCTION RETURN MULTIPLE VALUES IN PYTHON?

# YES,A FUNCTION CAN RETURN MULTIPLE VALUES IN PYTHON BY RETURNING THEM AS A TUPLE,LIST,OR DICTIONARY.

# 6.CAN A FUNCTION BE CALLED INSIDE ANOTHER FUNCTION ?

# YES,FUNCTION CAN CALL OTHER FUNCTIONS,EITHER FROM THE SAME MODULE OR FROM DIFFERENT MODULES.

# 7.WHAT IS A RECURSIVE FUNCTION?

# A RECURSIVE FUNCTION IS A FUNCTION THAT CALLS ITSELF DIRECTLY OR INDIRECTLY IN ORDER TO SOLVE A PROBLEM.
# IT USUALLY CONTAINS A BASE CASE TO TERMINATE THE RECURSION..

# 8.CAN FUNCTIONS IN PYTHON HAVE DEFAULT ARGUMENTS?

# YES,FUNCTION IN PYTHON CAN HAVE DEFAULT ARGUMENTS,WHICH ARE USED WHEN THE CALLER DOESNOT PROVIDE A VALUE 
# FOR THAT ARGUMENT.
    