#OBJECT ORIENTED PROGRAMMING STRUCTURE(BOTTOM UP APPROACH)(CLASS IS CREATED)
#INCREASES REUSABILITY
#POP-PROCEDURE ORIENTED PROGRAMMING(NO OOP'S)(TOP DOWN APPROACH)(PROBLEM DIVIDES)
#CLASS IS CREATED USING CLASS KEYWORD
#VARIABLES IN CLASSS ARE CALLED DATA MEMBERS
#FUNCTIONS IN CLASS ARE MEMBER FUCTIONS
#CONSTRUCTOR IS USED TO INITIALIZE VALUES TO VARIABLES/DATA MEMBERS OF THE CLASS...WHENEVER OBJECT IS MADE CONSTRUCTOR WILL IVOKE
#IN PYTHON CONSTRUCTOR IS MADE WITH __init__():


